### ISSUE TITLE
Windows client logging out after a few seconds

### ISSUE THREAD

**Issue by Yeomans** [Libki/libki-client#14]
Hi,

I posted this as a comment to a closed issue (#5) but figured I'd open a new one in case it gets missed. 

This issue still seems to be present with the newer clients.

I used the new installer on Ubuntu 18.04 because I was having dependency issues with the old one.

Nightly, 16.11, 16.04, all reset the timer to 0 after a few seconds. Was first using a Windows 10 vm but then tried on Windows 7 hardware (which is what will be used currently) and was having the exact same issue.

14.02 doesn't have this issue but instead does not count down...

**Comment by loidor** [comment]
All right, I'll look in to that.

If you log in to the server, is the user's time all gone or does it still have its time left?

**Comment by loidor** [comment]
Don't know if you saw it, but the timer not counting down was a server-side bug that's been taken care of. If you don't want to reinstall your server, edit ```/home/libki/libki-server/log4perl.conf``` and change ```/tmp/``` to ```/var/log/libki/```.

**Comment by Yeomans** [comment]
Thanks, I did see it.

If I check under the Clients tab all the data in the fields get removed but the PC name remains.

**Comment by loidor** [comment]
@kylemhall I think I'm going to need your assistance with this one.

All installers after Leela 14.02 has the #9 bug, but when I download the source and make a fresh build, the bug is gone and everything works as espected.

Could you please make a new installer (since I found another bug with the explorer acting up that's been patched)? I think that would solve it and that we'd have a stable client :)

**Comment by loidor** [comment]
@kylemhall, did you see this one? If it's lots of work I could post a patch for the time being.

**Comment by bwicksall** [comment]
I did a fresh Windows client compile today and I noticed that this issue was still present.  Looking at history I see there was a commit 3 days ago that seems to revert a fix from a few months ago:

commit: dbac639d8f439d95706193c2b27727eef7dc7113

I reverted the latest commit and now the client seems to work well with limited testing.

**Comment by kylemhall** [comment]
@bwicksall can you tell me what platform you are compiling on, and what version of qt? I'm compiling on Windows 7 Pro using Qt 5.3. I'm wondering if this is a bug of some kind in Qt. I cannot otherwise explain why one line of code 'fixes' this issue for me, and 'breaks' it for you ( with the previous version of the line doing the inverse ).

**Comment by bwicksall** [comment]
@kylemhall I'm compiling and running the client on Windows 10.  Qt version is 5.3.

**Comment by kylemhall** [comment]
@bwicksall can you test this installer: https://github.com/Libki/libki-client/releases/download/roberto-2018-06-07/Libki_Client_2c9fbad3544f3e40ef97d24af753a084ae3b100f_Installer.exe

It has the latest build of libkiclient.exe. If it works for you, then it must be some difference in our build environments.

**Comment by bwicksall** [comment]
@kylemhall That build works fine.  The file size is exactly the same as my build from yesterday.

**Comment by kylemhall** [comment]
@bwicksall FYI, don't bother testing that installer yet. It's borked. It looks like I need to include the dlls from the build environment instead of the ones I had saved myself.

**Comment by bwicksall** [comment]
@kylemhall Just let me know.  I'd be happy to test!

**Comment by kylemhall** [comment]
Ok! @bwicksall @Libki/libki-development-team I was able to change the build to use the correct DLLs from the build system itself. The added benefit being I was able to remove the included DLLs from the git repo saving a lot of space ( I rewrote the recent git history to get rid of them historically so make sure to do a git fetch and checkout of master before doing anything else with the client code locally ).

The current 'unstable' setup build using the current master can be found at https://github.com/Libki/libki-client/releases

Each unstable release has the associated commit id in its name. For some reason they are necessarily in order by newest at the top for some reason. Just an FYI.

Now we have a Libki client and installer that is built on nobodies local machine. We should now consider this the canonical version. If there is a conflict of code between this build and anyone else's build ( including mine ) this one wins ; )

As of my testing it appears to function correctly. I should also note it is built using Qt 5.5 rather than the Qt 5.3 we have been using. I think we should all probably all move to that version.

The latest version of Qt available on AppVeyor is Qt 5.11.1, if anyone is brave enough to try moving the code to that version I'd be happy to help!

**Comment by loidor** [comment]
Great job! Apparently I needed my VM space for something else, but I'll see if I come around to set it up this weekend.

**Comment by kylemhall** [comment]
Also, I should not along with Qt 5.5, the build is using mingw 492_32. The closer our dev environments are to the build environment the better ;)

**Comment by loidor** [comment]
I got curious and setup a new one, and the bug is there for me now with the current installer. That's win7 sp1. For what it's worth it's US english with Swedish localization (I doubt that has anything to do with it though). I have a win10 disc as well, so I'll give that a try next.

**Comment by loidor** [comment]
Tried the current commit on my Linux Mint 19 machine, and got the same issue. I made a log:
```
NetworkClient::getUserDataUpdate
NetworkClient::processGetUserDataUpdateReply
Server Result:  "{\"units\":45,\"messages\":[],\"status\":\"Logged in\"}"
STATUS:  "Logged in"
MESSAGE ARRAY SIZE:  0
UNITS:  0
TimerWindow::updateTimeLeft(  0  )
TimerWindow::updateClock
NetworkClient::attemptLogout
NetworkClient::doLogoutTasks
TimerWindow::stopTimer
```

However if I run the "old commit" (5383372 to be precise), it works and this is that log:
```
NetworkClient::getUserDataUpdate
NetworkClient::processGetUserDataUpdateReply
Server Result:  "{\"units\":45,\"status\":\"Logged in\",\"messages\":[]}"
STATUS:  "Logged in"
MESSAGE ARRAY SIZE:  0
UNITS:  45
TimerWindow::updateTimeLeft(  45  )
TimerWindow::updateClock
```

So I'm really sorry Kyle, but it looks like your environment is the iffy one here.

**Comment by loidor** [comment]
I might've got a solution. First a short recap.

`toString().toInt()` breaks it for me and Bob.
`toInt()` breaks it for Kyle.

So apparently there's something going on with the json object data not really being a perfect integer or a perfect string, so I googled around for a bit and found this thread on Stack overflow (second part of top answer is the interesting bit): https://stackoverflow.com/questions/22474654/how-to-retrieve-integer-value-from-json-data-in-qt

`toVariant().toInt()` works for me, so with a _little_ bit of luck this works for you too, @kylemhall. Try it out and see what happens.

**Comment by kylemhall** [comment]
Interesting! Let's try it!

**Comment by kylemhall** [comment]
In my current 5.3 dev environment, toVariant does not seem applicable to a QJsonValueRef object :\

**Comment by loidor** [comment]
Ah. I upgraded my computer a month or so ago (mint 19, so ubuntu bionic based), and apparently I'm running 5.9 now. Didn't check that yesterday. I'll have a look to see if I can come around it in some other way in 5.3.

**Comment by kylemhall** [comment]
I just found a way to convert the variable to a variant before converting to an int. Let's hope this works for everyone!

**Comment by loidor** [comment]
Works beautifully. Great! :1st_place_medal: 

Mark this one as stable and give it a nice name, I say.

**Comment by kylemhall** [comment]
Sounds like a plan! I think I'll try to finish the manual as the final thing to do before making this release!

**Comment by loidor** [comment]
Perfect!

**Comment by bwicksall** [comment]
Just installed the latest build and it works great in my environment!  Thanks!
