### ISSUE TITLE
Setting the opening hours ?

### ISSUE THREAD

**Issue by mwhited07** [Libki/libki-client#41]
I can see an option for setting the closing time on the server for certain days of the week.  Is it  possible to have the server autologout the clients, forcing a reboot at that time?

Also, is there a way to adjust the starting time?   I only see closing time.  I have a branch that opens at 7 am, so I would like the service to close at 6 pm, open at 7 am.

**Comment by loidor** [comment]
At closing time, the clients will logout automatically, so that's how it works. 

The opening time is default set to when the nightly script is run - usually, this means the clients are open for login when the library opens. So there's never been a need for opening times before. From the setup you describe, I think this will work prefectly for your needs as well.
