### ISSUE TITLE
Unable to edit "Libki Kiosk Management System.ini"

### ISSUE THREAD

**Issue by TypicalLibrarian** [Libki/libki-client#7]
I am currently running libki on laptop (with windows 10 home) to test the software. I'm connected to my server, so i'm wanting to mess with the more complicated settings, however every time I attempt to edit the "Libki Kiosk Management System.ini" file (the ProgramData one, not %AppData%) I get an "Access is Denied" error. I'm aware that this is a windows problem, however I have tried accessing the file as Administrator, I've disabled "read-only", I'm hoping someone else has run into this.

**Comment by aprilwhittle** [comment]
Yoe would have to open it as admin in windows ti edit

**Comment by TypicalLibrarian** [comment]
I don't see the option to run/open/edit as admin, even though that's the account I am on.

**Comment by aprilwhittle** [comment]
Right clicking the icon will bring up a list of options or should if I
recall.  If you have what your editing it open already that has to be run
as admin to edit.  Been awhile I usually work in linux

On Jun 24, 2017 12:53 PM, "TypicalLibrarian" <notifications@github.com>
wrote:

I don't see the option to run/open/edit as admin, even though that's the
account I am on.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/Libki/libki-client/issues/7#issuecomment-310862107>,
or mute
the thread

**Comment by aprilwhittle** [comment]
Try runing the editor first as admin then open the ini to edit

**Comment by TypicalLibrarian** [comment]
Thank Zeus, that did it. Thanks, and sorry for the dumb question, I tried everything but the obvious.
